name: Publish to Snapcraft Store
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
        with:
          token: ${{ secrets.PAT }}
      - uses: actions/setup-node    
      - run: npm ci
      - run: npm run sync
      - uses: stefanzweifel/git-auto-commit-action@v4